export const mocks = {
  viewMore: [
    {
      id: 1,
      title: 'Interior Design',
      content: 'Enhancing the interior to achieve a healthier environment for the people using right space.',
    },
    {
      id: 2,
      title: 'Furniture',
      content: 'Movable articles that are used to make a room or building suitable for living or working.',
    },
    {
      id: 3,
      title: 'Flooring',
      content: 'Thin object any finished material applied over a floor structure to provide a walking surface.',
    },
  ],

  screenPeopleAbout: [
    {
      id: 1,
      avatar: '/users/user1.jpg',
      name: 'Lisa',
      surname: 'Clairton',
      city: 'New York',
      country: 'USA',
      content: 'We selected Interno interior because of rigorous design background & education.',
    },
    {
      id: 2,
      avatar: '/users/user2.jpg',
      name: 'David',
      surname: 'Knight',
      city: 'Sydney',
      country: 'Australia',
      content: 'The team exceeded our expectations and emerged as leaders of our project’s.',
    },
    {
      id: 3,
      avatar: '/users/user3.jpg',
      name: 'Anna',
      surname: 'Shepard',
      city: 'Paris',
      country: 'France',
      content: 'They balanced the architectural vision and the project realities beautifully.',
    },
  ],
  recentProjects: [
    {
      id: 1,
      url: '',
      img: '/images/img_001.jpg',
      categoryId: 1,
      category: 'Art Modern',
      name: 'Winery Dry Creek Building',
    },
    {
      id: 2,
      url: '',
      img: '/images/img_002.jpg',
      categoryId: 2,
      category: 'Minimalist',
      name: 'Creative Workplace Design',
    },
    {
      id: 3,
      url: '',
      img: '/images/img_003.jpg',
      categoryId: 3,
      category: 'Art Modern',
      name: 'Winery Dry Creek Building',
    },
    {
      id: 4,
      url: '',
      img: '/images/img_004.jpg',
      categoryId: 4,
      category: 'Art Modern',
      name: 'Winery Dry Creek Building',
    },
  ],
  recentBlogs: [
    {
      id: 1,
      category: 'Kitchen Design',
      title: 'Residential Interior Designer In New York, USA',
      date: 'November 23, 2021',
      img: '/images/img_005.jpg',
    },
    {
      id: 2,
      category: 'Living Room',
      title: 'How To Choose The Best Wall Art & Decor House?',
      date: 'November 23, 2021',
      img: '/images/img_006.jpg',
    },
    {
      id: 3,
      category: 'Minimalist Interior',
      title: 'Tips To Increase The Interior Value Of Your House',
      date: 'November 23, 2021',
      img: '/images/img_007.jpg',
    },
    {
      id: 4,
      category: 'Kitchen Design',
      title: 'Best Solution For Any Office & Business Interior',
      date: 'November 23, 2021',
      img: '/images/img_008.jpg',
    },
    {
      id: 5,
      category: 'Living Room',
      title: 'Get Solution For Building Construction Work',
      date: 'November 23, 2021',
      img: '/images/img_009.jpg',
    },
    {
      id: 6,
      category: 'Minimalist Interior',
      title: 'Attain The Best Finish For The Kitchen Cabinets',
      date: 'November 23, 2021',
      img: '/images/img_010.jpg',
    },
  ]
};